apiVersion: v1
kind: Service
metadata:
  name: longpoll-app
  labels:
    app: longpoll-app
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      # Optional
      # By default and for convenience, the k8s control plane will allocate a port from a range (default: 30000-32767)
      nodePort: 30080
  selector:
    app: longpoll-app

